# Generated by Django 5.2.3 on 2025-06-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('company', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('task', models.TextField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('memo', models.TextField(blank=True)),
            ],
        ),
    ]
