# Generated by Django 5.2.3 on 2025-07-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyreport',
            name='company',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='date',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='memo',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='product',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='task',
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='作業時間',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
