# Generated by Django 5.2.3 on 2025-07-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_dailyreport_company_remove_dailyreport_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='company',
            field=models.CharField(default='未設定', max_length=100),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='date',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='end_time',
            field=models.TimeField(default='05:31'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='memo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='product',
            field=models.CharField(default='未設定', max_length=100),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='start_time',
            field=models.TimeField(default='05:30'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='task',
            field=models.TextField(default='未設定'),
        ),
    ]
