# Generated by Django 5.2.3 on 2025-08-03 05:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_dailyreport_company_dailyreport_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
