# Generated by Django 5.2.3 on 2025-08-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_company_task_dailyreport_task_fk_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('product', models.CharField(blank=True, max_length=100, null=True)),
                ('sort_order', models.PositiveIntegerField(default=1000)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
    ]
