# Generated by Django 5.2.3 on 2025-09-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_taskpreset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyreport',
            options={'ordering': ['date', 'start_time', 'id']},
        ),
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['date'], name='main_dailyr_date_0ced47_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['start_time'], name='main_dailyr_start_t_bd145b_idx'),
        ),
    ]
